/***
 * @Author: LiHeng
 * @Date: 2024-03-14 16:05:16
 * @LastEditors: LiHeng
 * @LastEditTime: 2024-05-28 09:05:38
 * @FilePath: /rt1170_rtems_source_1176/bsps/arm/imxrt/boards/evkimxrt1170/dcd.h
 * @Description:
 * @
 * @Copyright (c) 2024 by LiHeng, All Rights Reserved.
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef __DCD__
#define __DCD__

#include <stdint.h>

/*! @name Driver version */
/*@{*/
/*! @brief XIP_BOARD driver version 2.0.0. */
#define FSL_XIP_BOARD_DRIVER_VERSION (MAKE_VERSION(2, 0, 0))
/*@}*/

/*************************************
 *  DCD Data
 *************************************/
#define DCD_TAG_HEADER (0xD2)
#define DCD_VERSION (0x41)
#define DCD_TAG_HEADER_SHIFT (24)
#define DCD_ARRAY_SIZE 1

#endif /* __DCD__ */
